### PR TITLE
Add aws credentials into accepter and requester providers

### PR DESCRIPTION
**Pull request by heruscode**
## what
* Adds AWS credentials variables into providers ( access key id, secret access key, session token)

## why
* I have a use case of using Hashicorp Vault to fetch AWS credentials, i need a way to pass these fetched credentials into the module.

### CODE REVIEW

**Comment by nitrocode** [comment]
It would be better to keep the defaults `null` for each variable

**Comment by heruscoder** [comment]
Done, thank you

**Comment by heruscoder** [comment]
I think this commit fixes the test @nitrocode

**Comment by heruscoder** [comment]
I think i don't know what needs to be done, could you help me?

**Comment by SweetOps** [comment]
could you run the following commands locally and commit:

```
make init
make readme
terraform fmt
```

**Comment by heruscoder** [comment]
Done!

**Review by SweetOps — APPROVED** [review]

**Pull request merged**
