### PR TITLE
Refactor requester.tf to use aws_route_tables data source

### PR DESCRIPTION
**Pull request by vquie**
## what

- Replaced the "aws_route_table" data source with "aws_route_tables" for better handling of multiple route tables in the VPC.
- Added a filter to the "aws_route_tables" data source to only include route tables associated with the subnets in the VPC.
- Updated dependencies in the "aws_route" resource to reflect the change in data source.

## why

All my VPCs with more then one subnet raised this error.

```
Error: query returned no results. Please change your search criteria and try again

  with module.vpc_vpn_vpc_peering.data.aws_route_table.requester[5],
  on .terraform/modules/vpc_vpn_vpc_peering/requester.tf line 124, in data "aws_route_table" "requester":
 124: data "aws_route_table" "requester" {
```

## references

https://sweetops.slack.com/archives/CB6GHNLG0/p1694006033839549

### CODE REVIEW

**Comment by max-lobur** [comment]
Please run `make precommit/terraform` and commit the changes, this should fix all the linters

**Comment by max-lobur** [comment]
I've merged the baseline fixes, and don’t know the fix for the current error yet. It’s also in main branch
https://github.com/cloudposse/actions/actions/runs/6216155331/job/16869736066
I thought this PR was to address it but no, it's different. Will recheck this week

**Comment by vquie** [comment]
> Please run `make precommit/terraform` and commit the changes, this should fix all the linters

Done. Thanks.

**Comment by tfendt-belong-gg** [comment]
I am getting this same error, can this get merged?

**Comment by vquie** [comment]
@aknysh 

Unfortunately this failed on my machine.

```
❯ make readme
* Installing packages master...
Cloning into '/Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor/packages'...
remote: Enumerating objects: 942, done.
remote: Counting objects: 100% (942/942), done.
remote: Compressing objects: 100% (451/451), done.
remote: Total 942 (delta 335), reused 627 (delta 251), pack-reused 0
Receiving objects: 100% (942/942), 11.23 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (335/335), done.
* Installing gomplate to /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor
mkdir -p -m a+rX /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor
curl --retry 3 --retry-delay 5 --fail -sSL -o /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.11.7/gomplate_darwin-arm64 && chmod +x /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor/gomplate
* Installing terraform-docs to /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor
mkdir -p -m a+rX /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor
[ -n "/tmp" ] && [ -n "terraform-docs" ] && rm -rf "/tmp/terraform-docs"
mkdir -p /tmp/terraform-docs
curl --retry 3 --retry-delay 5 --fail -sSL -o - https://github.com/segmentio/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-darwin-arm64.tar.gz | tar -zx -C /tmp/terraform-docs
find /tmp/terraform-docs -type f -name terraform-docs | xargs -I {} cp -f {} /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor/terraform-docs
chmod +x /Users/homefolder/git/github/terraform-aws-vpc-peering-multi-account/build-harness/vendor/terraform-docs
[ -n "/tmp" ] && [ -n "terraform-docs" ] && rm -rf "/tmp/terraform-docs"
make: gomplate: No such file or directory
make: *** [readme/build] Error 1
```

Any ideas?

**Comment by vquie** [comment]
@aknysh, thanks. I should've figured that out myself. 🤦 

The command went through successfully and the new changes are pushed.

**Pull request closed without merging**
